version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "AWSSDK*"
      - dependency-name: "Pulumi*"
  - package-ecosystem: docker
    directory: /Cli
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
