---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-auth
data:
  mapRoles: |
    - rolearn: {{ nodeRoleArn }}
      username: system:node:{{ '{{' }}EC2PrivateDNSName{{ '}}' }}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: {{ deployerRoleArn }}
      username: deployer
      groups:
        - system:masters
