---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: environment-sysctl
spec:
  allowPrivilegeEscalation: false
  allowedUnsafeSysctls:
    - net.ipv4.ip_unprivileged_port_start
  allowedCapabilities:
    - NET_ADMIN
  volumes:
    - "*"
  hostNetwork: false
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: environment-sysctl
rules:
  - apiGroups:
      - policy
    resourceNames:
      - environment-sysctl
    resources:
      - podsecuritypolicies
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ envName }}
  name: environment-sysctl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: environment-sysctl
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
